#1 translate descriptions
CheckIO-to-German/Battle-Dice pull request #2
Opened 2016-11-06 23:46 UTC by GiForce

2016-11-07 20:54 UTC, DahliaSR requested changes
Review 1

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Es hat mindestens einen Angriff auf einem ganzen Würfel <br/>
- **Von:** _hat mindestens einen Angriff auf einem ganzen Würfel_  
  **Zu:** _**gibt** mindestens einen Angriff auf einem Würfel**.**_ (punkt beachten)  
  ==> halbe Würfel wären eigenartig :scissors:

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Dieser Art mehrstufigen Wahrscheinlichkeitsberechnungen sind beliebt in Programmierwettkämpfen und Wahrscheinlichkeits-Lehrbüchern.
- **Von:** _Dieser Art mehrstufigen Wahrscheinlichkeitsberechnungen sind beliebt in Programmierwettkämpfen und Wahrscheinlichkeits-Lehrbüchern._  
  **Zu:** _**Diese** Art **mehrstufiger** Wahrscheinlichkeitsberechnungen **ist** beliebt in Programmierwettkämpfen und **Wahrscheinlichkeitslehrbüchern**._

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    <strong>Beispiel:</strong>
- **Von:** _Beispiel_  
  **Zu:** _Beispiel**e**_  
  ==> Plural!

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    <strong>Eingabe:</strong> Drei Argumente. Eine Beschreibung des Würfels als eine Liste von Strings. Die Anzahl Einheiten
- **Von:** _Die Anzahl Einheiten_  
  **Zu:** _Die Anzahl **der** Einheiten_

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Du musst die Wahrscheinlichkeit für Spieler Eins berechnen den Konflikt zu gewinnen.
- **Von:** _Du musst die Wahrscheinlichkeit für Spieler Eins berechnen den Konflikt zu gewinnen._  
  **Zu:** _Du musst die Wahrscheinlichkeit für einen Sieg von Spieler Eins berechnen._  
  ==> liest sich leichter

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Nach einem Wurf, zieht man die Anzahl gewürfelter Verteidigunszeichen von den gegnerischen Angriffszeichen ab, und hat
- **Von:** _Nach einem Wurf_  
 **Zu:** _Nach **jeder Runde**_  
 ==> es wird einmal pro einheit gewürfelt

2016-11-07 20:54 UTC, DahliaSR commented on translations/de/info/task_short_description.html
> +Schlacht über die Kontrolle der Würfel!
- **Von:** _Schlacht über die Kontrolle der Würfel!_  
 **Zu:** _Schlacht **um** die Kontrolle der Würfel!_  
 ==>

2016-11-10 12:04 UTC, GiForce commented on translations/de/info/task_description.html
> +    Nach einem Wurf, zieht man die Anzahl gewürfelter Verteidigunszeichen von den gegnerischen Angriffszeichen ab, und hat
☑️

2016-11-10 12:06 UTC, GiForce commented on translations/de/info/task_description.html
> +    Du musst die Wahrscheinlichkeit für Spieler Eins berechnen den Konflikt zu gewinnen.
☑️

2016-11-10 12:07 UTC, GiForce commented on translations/de/info/task_description.html
> +    <strong>Eingabe:</strong> Drei Argumente. Eine Beschreibung des Würfels als eine Liste von Strings. Die Anzahl Einheiten
☑️

2016-11-10 12:07 UTC, GiForce commented on translations/de/info/task_description.html
> +    <strong>Beispiel:</strong>
☑️

2016-11-10 12:08 UTC, GiForce commented on translations/de/info/task_description.html
> +    Dieser Art mehrstufigen Wahrscheinlichkeitsberechnungen sind beliebt in Programmierwettkämpfen und Wahrscheinlichkeits-Lehrbüchern.
☑️

2016-11-10 12:09 UTC, GiForce commented on translations/de/info/task_description.html
> +    Es hat mindestens einen Angriff auf einem ganzen Würfel <br/>
☑️

2016-11-10 12:12 UTC, GiForce commented on translations/de/info/task_short_description.html
> +Schlacht über die Kontrolle der Würfel!
☑️

2016-11-10 20:30 UTC, DahliaSR approved these changes

2016-11-10 20:43 UTC, merged